# Generated by Django 3.2.11 on 2022-02-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bucket',
            field=models.CharField(choices=[('quality', 'Quality'), ('engineering', 'Engineering'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default='NO Subject', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='summary',
            field=models.CharField(default='NO Summary', max_length=500),
        ),
    ]
